spring:
  application:
    name: ISD-Project
    group: 6
    author: Thienpv
#  jpa:
#      show-sql: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/isd_final
#    username: root
#    password: 1234
  data:
    mongodb:
#      uri: url-example  // db test
#      database: sample_mflix
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
              MongoTemplate: DEBUG

server:
  port: 8888
  servlet:
        context-path: /api